In [1]:
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import Perceptron
import sklearn.metrics as metric
import numpy as np

In [2]:
X_training=[[1, 1],
 [1, 0],
 [0, 1],
 [0, 0]
 ]
y_training=[1,
 1,
 1,
 0
 ]
X_testing=X_training
y_true=y_training

In [3]:
ptn = Perceptron(max_iter=500) # set the method
ptn.fit(X_training, y_training) # training
y_pred=ptn.predict(X_testing) # prediction
print(y_pred) # show the output
accuracy=metric.accuracy_score(y_true, y_pred, normalize=True)
print('acuracy=',accuracy) # show accracy score

[1 1 1 0]
acuracy= 1.0


In [4]:
print(ptn.intercept_, ptn.coef_) # show the synapsis weights w0, w1, w2, ...

[-1.] [[2. 2.]]


In [6]:
mlp = MLPClassifier(solver='lbfgs', hidden_layer_sizes=(1,1), activation='logistic') #set the method
mlp.fit(X_training, y_training) # training
y_pred=mlp.predict(X_testing) # prediction
print(y_pred) # show the output
accuracy=metric.accuracy_score(np.array(y_true).flatten(), np.array(y_pred).flatten(),
normalize=True)
print('acuracy=',accuracy) # show accracy score

[1 1 1 0]
acuracy= 1.0


In [7]:
print([coef.shape for coef in mlp.coefs_]) # size of synapsis weights
mlp.coefs_ # synapsis weights

[(2, 1), (1, 1), (1, 1)]


[array([[4.09394745],
        [4.31844729]]),
 array([[8.04993388]]),
 array([[15.02574918]])]

# 1. Bipolar OR 

In [8]:
X_training=[[1, 1],
 [1, -1],
 [-1, 1],
 [-1, -1]
 ]
y_training=[1,
 1,
 1,
 -1
 ]
X_testing=X_training
y_true=y_training 
ptn = Perceptron(max_iter=500) # set the method
ptn.fit(X_training, y_training) # training
y_pred=ptn.predict(X_testing) # prediction
print(y_pred) # show the output
accuracy=metric.accuracy_score(y_true, y_pred, normalize=True)
print('acuracy=',accuracy) # show accracy score
mlp = MLPClassifier(solver='lbfgs', hidden_layer_sizes=(1,1), activation='logistic') #set the method
mlp.fit(X_training, y_training) # training
y_pred=mlp.predict(X_testing) # prediction
print(y_pred) # show the output
accuracy=metric.accuracy_score(np.array(y_true).flatten(), np.array(y_pred).flatten(),
normalize=True)
print('acuracy=',accuracy) # show accracy score

[ 1  1  1 -1]
acuracy= 1.0
[ 1  1  1 -1]
acuracy= 1.0


# 2. AND gate

In [9]:
X_training=[[1, 1],
 [1, 0],
 [0, 1],
 [0, 0]
 ]
y_training=[1,
 0,
 0,
 0
 ]
X_testing=X_training
y_true=y_training 
ptn = Perceptron(max_iter=500) # set the method
ptn.fit(X_training, y_training) # training
y_pred=ptn.predict(X_testing) # prediction
print(y_pred) # show the output
accuracy=metric.accuracy_score(y_true, y_pred, normalize=True)
print('acuracy=',accuracy) # show accracy score
mlp = MLPClassifier(solver='lbfgs', hidden_layer_sizes=(1,1), activation='logistic') #set the method
mlp.fit(X_training, y_training) # training
y_pred=mlp.predict(X_testing) # prediction
print(y_pred) # show the output
accuracy=metric.accuracy_score(np.array(y_true).flatten(), np.array(y_pred).flatten(),
normalize=True)
print('acuracy=',accuracy) # show accracy score

[1 0 0 0]
acuracy= 1.0
[1 0 0 0]
acuracy= 1.0


# 3. Bipolar AND gate 

In [11]:
X_training=[[1, 1],
 [1, -1],
 [-1, 1],
 [-1, -1]
 ]
y_training=[1,
 -1,
 -1,
 -1
 ]
X_testing=X_training
y_true=y_training 
ptn = Perceptron(max_iter=500) # set the method
ptn.fit(X_training, y_training) # training
y_pred=ptn.predict(X_testing) # prediction
print(y_pred) # show the output
accuracy=metric.accuracy_score(y_true, y_pred, normalize=True)
print('acuracy=',accuracy) # show accracy score
mlp = MLPClassifier(solver='lbfgs', hidden_layer_sizes=(1,1), activation='logistic') #set the method
mlp.fit(X_training, y_training) # training
y_pred=mlp.predict(X_testing) # prediction
print(y_pred) # show the output
accuracy=metric.accuracy_score(np.array(y_true).flatten(), np.array(y_pred).flatten(),
normalize=True)
print('acuracy=',accuracy) # show accracy score

[ 1 -1 -1 -1]
acuracy= 1.0
[ 1 -1 -1 -1]
acuracy= 1.0


# 4. Two output neurons 

In [12]:
X_training=[[1, 1],
 [1, 0],
 [0, 1],
 [0, 0]
 ]
y_training=[[1, 1],
 [1, 1],
 [1, 1],
 [0, 1]
 ]
X_testing=X_training
y_true=y_training 
ptn = Perceptron(max_iter=500) # set the method
ptn.fit(X_training, y_training) # training
y_pred=ptn.predict(X_testing) # prediction
print(y_pred) # show the output
accuracy=metric.accuracy_score(y_true, y_pred, normalize=True)
print('acuracy=',accuracy) # show accracy score
mlp = MLPClassifier(solver='lbfgs', hidden_layer_sizes=(1,1), activation='logistic') #set the method
mlp.fit(X_training, y_training) # training
y_pred=mlp.predict(X_testing) # prediction
print(y_pred) # show the output
accuracy=metric.accuracy_score(np.array(y_true).flatten(), np.array(y_pred).flatten(),
normalize=True)
print('acuracy=',accuracy) # show accracy score

ValueError: y should be a 1d array, got an array of shape (4, 2) instead.

# y should be a 1d array, got an array of shape (4, 2) instead.


# 5. XOR

In [24]:
X_training=[[1, 1],
 [1, 0],
 [0, 1],
 [0, 0]
 ]
y_training=[1,
 0,
 0,
 1
 ]
X_testing=X_training
y_true=y_training 
ptn = Perceptron(max_iter=500) # set the method
ptn.fit(X_training, y_training) # training
y_pred=ptn.predict(X_testing) # prediction
print(y_pred) # show the output
accuracy=metric.accuracy_score(y_true, y_pred, normalize=True)
print('acuracy=',accuracy) # show accracy score
mlp = MLPClassifier(solver='lbfgs', hidden_layer_sizes=(3,2), activation='logistic') #set the method
mlp.fit(X_training, y_training) # training
y_pred=mlp.predict(X_testing) # prediction
print(y_pred) # show the output
accuracy=metric.accuracy_score(np.array(y_true).flatten(), np.array(y_pred).flatten(),
normalize=True)
print('acuracy=',accuracy) # show accracy score

[0 0 0 0]
acuracy= 0.5
[1 0 0 1]
acuracy= 1.0


# If we add more layers in the hidden layer we will get more acurate result.

# 6. Neural Network with 3 input and 2 output 

In [29]:
X_training=[[ 1, 1, 0],
 [ 1, -1, -1],
 [-1, 1, 1],
 [-1, -1, 1],
 [ 0, 1, -1],
 [ 0, -1, -1],
 [ 1, 1, 1]
 ]
y_training=[[1, 0],
 [0, 1],
 [1, 1],
 [1, 0],
 [1, 0],
 [1, 1],
 [1, 1]
 ]
X_testing=X_training
y_true=y_training 
mlp = MLPClassifier(solver='lbfgs', hidden_layer_sizes=(3,2), activation='logistic') #set the method
mlp.fit(X_training, y_training) # training
y_pred=mlp.predict(X_testing) # prediction
print(y_pred) # show the output
accuracy=metric.accuracy_score(np.array(y_true).flatten(), np.array(y_pred).flatten(),
normalize=True)
print('acuracy=',accuracy) # show accracy score

[[1 0]
 [0 1]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 1]]
acuracy= 1.0
